[package]
name = "mlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math_lang_lib = { version = "0.1.0", path = "../math_lang_lib" }
